// @ts-check

import { traverse, types } from '@babel/core';
import { generate } from '@babel/generator';
import parser from '@babel/parser';
import fs from 'fs/promises';
import { deobfuscate } from 'obfuscator-io-deobfuscator';

const originalScript = await fs.readFile('./orig_scripts/_Incapsula_Resource.js.txt', {
    encoding: 'utf-8',
});

const ast = parser.parse(originalScript);

const calls = [];
traverse(ast, {
    CallExpression(path) {
        if (
            path.node.callee.type === 'Identifier' &&
            path.node.callee.name === '_0x32f1' &&
            path.node.arguments.length === 2 &&
            path.node.arguments.every((arg) => arg.type === 'StringLiteral')
        ) {
            calls.push({
                firstArg: path.node.arguments[0].value,
                secondArg: path.node.arguments[1].value,
                script: `_0x32f1("${path.node.arguments[0].value}", "${path.node.arguments[1].value}")`,
            });
        }
    },
});

console.log('Extracted _0x32f1 calls:', calls);

const callsWithValues = [
    {
        firstArg: '0x0',
        secondArg: '4!X[',
        script: '_0x32f1("0x0", "4!X[")',
        result: 'window',
    },
    {
        firstArg: '0x1',
        secondArg: 'EECj',
        script: '_0x32f1("0x1", "EECj")',
        result: 'document',
    },
    {
        firstArg: '0x2',
        secondArg: 'plp9',
        script: '_0x32f1("0x2", "plp9")',
        result: 'NvK',
    },
    {
        firstArg: '0x3',
        secondArg: 'Y)S$',
        script: '_0x32f1("0x3", "Y)S$")',
        result: 'console',
    },
    {
        firstArg: '0x4',
        secondArg: 'Qv[c',
        script: '_0x32f1("0x4", "Qv[c")',
        result: 'undefined',
    },
    {
        firstArg: '0x5',
        secondArg: '0MG!',
        script: '_0x32f1("0x5", "0MG!")',
        result: 'console',
    },
    {
        firstArg: '0x6',
        secondArg: 'qMq4',
        script: '_0x32f1("0x6", "qMq4")',
        result: 'log',
    },
    {
        firstArg: '0x7',
        secondArg: '6)P!',
        script: '_0x32f1("0x7", "6)P!")',
        result: 'navigator',
    },
    {
        firstArg: '0x8',
        secondArg: 'fjzy',
        script: '_0x32f1("0x8", "fjzy")',
        result: 'encodeURIComponent',
    },
    {
        firstArg: '0x9',
        secondArg: 'TER%',
        script: '_0x32f1("0x9", "TER%")',
        result: 'Date',
    },
    {
        firstArg: '0xa',
        secondArg: ']uNf',
        script: '_0x32f1("0xa", "]uNf")',
        result: 'getTime',
    },
    {
        firstArg: '0xb',
        secondArg: 'SB@Q',
        script: '_0x32f1("0xb", "SB@Q")',
        result: '2|0|5|1|7|4|3|6',
    },
    {
        firstArg: '0xc',
        secondArg: 'hHMm',
        script: '_0x32f1("0xc", "hHMm")',
        result: 'split',
    },
    {
        firstArg: '0xd',
        secondArg: 'E[@b',
        script: '_0x32f1("0xd", "E[@b")',
        result: 'length',
    },
    {
        firstArg: '0xe',
        secondArg: 'Y(gg',
        script: '_0x32f1("0xe", "Y(gg")',
        result: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',
    },
    {
        firstArg: '0xf',
        secondArg: 'RCFI',
        script: '_0x32f1("0xf", "RCFI")',
        result: 'sQn',
    },
    {
        firstArg: '0x10',
        secondArg: '6V&2',
        script: '_0x32f1("0x10", "6V&2")',
        result: '0|3|4|1|5|2|8|7|6',
    },
    {
        firstArg: '0x11',
        secondArg: 'M6RB',
        script: '_0x32f1("0x11", "M6RB")',
        result: 'split',
    },
    {
        firstArg: '0x12',
        secondArg: 'E[@b',
        script: '_0x32f1("0x12", "E[@b")',
        result: 'uLy',
    },
    {
        firstArg: '0x13',
        secondArg: 'nWG6',
        script: '_0x32f1("0x13", "nWG6")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x14',
        secondArg: 'Kax[',
        script: '_0x32f1("0x14", "Kax[")',
        result: 'xWt',
    },
    {
        firstArg: '0x15',
        secondArg: 'wSBw',
        script: '_0x32f1("0x15", "wSBw")',
        result: 'charAt',
    },
    {
        firstArg: '0x16',
        secondArg: 'B^5n',
        script: '_0x32f1("0x16", "B^5n")',
        result: 'Jud',
    },
    {
        firstArg: '0x17',
        secondArg: 'M6RB',
        script: '_0x32f1("0x17", "M6RB")',
        result: 'charAt',
    },
    {
        firstArg: '0x18',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x18", "SB@Q")',
        result: 'oBj',
    },
    {
        firstArg: '0x19',
        secondArg: '4hK1',
        script: '_0x32f1("0x19", "4hK1")',
        result: 'rFM',
    },
    {
        firstArg: '0x1a',
        secondArg: 'E[@b',
        script: '_0x32f1("0x1a", "E[@b")',
        result: 'rDR',
    },
    {
        firstArg: '0x1b',
        secondArg: '4hK1',
        script: '_0x32f1("0x1b", "4hK1")',
        result: 'Jud',
    },
    {
        firstArg: '0x1c',
        secondArg: 'Y)S$',
        script: '_0x32f1("0x1c", "Y)S$")',
        result: 'IRT',
    },
    {
        firstArg: '0x1d',
        secondArg: '6)P!',
        script: '_0x32f1("0x1d", "6)P!")',
        result: 'charAt',
    },
    {
        firstArg: '0x1e',
        secondArg: 'hAPU',
        script: '_0x32f1("0x1e", "hAPU")',
        result: 'rFM',
    },
    {
        firstArg: '0x1f',
        secondArg: 'eSAb',
        script: '_0x32f1("0x1f", "eSAb")',
        result: 'XMZ',
    },
    {
        firstArg: '0x20',
        secondArg: ']Y49',
        script: '_0x32f1("0x20", "]Y49")',
        result: 'charAt',
    },
    {
        firstArg: '0x21',
        secondArg: 'PVM9',
        script: '_0x32f1("0x21", "PVM9")',
        result: 'Jud',
    },
    {
        firstArg: '0x22',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x22", "SB@Q")',
        result: 'udv',
    },
    {
        firstArg: '0x23',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x23", "K]Ws")',
        result: 'charAt',
    },
    {
        firstArg: '0x24',
        secondArg: 'ieO2',
        script: '_0x32f1("0x24", "ieO2")',
        result: 'Jud',
    },
    {
        firstArg: '0x25',
        secondArg: '6V&2',
        script: '_0x32f1("0x25", "6V&2")',
        result: 'charAt',
    },
    {
        firstArg: '0x26',
        secondArg: 'qMq4',
        script: '_0x32f1("0x26", "qMq4")',
        result: 'JBi',
    },
    {
        firstArg: '0x27',
        secondArg: 'QA4[',
        script: '_0x32f1("0x27", "QA4[")',
        result: 'XMZ',
    },
    {
        firstArg: '0x28',
        secondArg: 'QA4[',
        script: '_0x32f1("0x28", "QA4[")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x29',
        secondArg: 'tmku',
        script: '_0x32f1("0x29", "tmku")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x2a',
        secondArg: 'hHMm',
        script: '_0x32f1("0x2a", "hHMm")',
        result: 'charAt',
    },
    {
        firstArg: '0x2b',
        secondArg: 'E[@b',
        script: '_0x32f1("0x2b", "E[@b")',
        result: 'XMZ',
    },
    {
        firstArg: '0x25',
        secondArg: '6V&2',
        script: '_0x32f1("0x25", "6V&2")',
        result: 'charAt',
    },
    {
        firstArg: '0x2c',
        secondArg: 'EECj',
        script: '_0x32f1("0x2c", "EECj")',
        result: 'oBj',
    },
    {
        firstArg: '0x2d',
        secondArg: '&%YX',
        script: '_0x32f1("0x2d", "&%YX")',
        result: 'qRH',
    },
    {
        firstArg: '0x2e',
        secondArg: 'y1KF',
        script: '_0x32f1("0x2e", "y1KF")',
        result: 'xgg',
    },
    {
        firstArg: '0x2f',
        secondArg: 'EECj',
        script: '_0x32f1("0x2f", "EECj")',
        result: 'Jud',
    },
    {
        firstArg: '0x30',
        secondArg: ']ecs',
        script: '_0x32f1("0x30", "]ecs")',
        result: 'charAt',
    },
    {
        firstArg: '0x31',
        secondArg: 'hHMm',
        script: '_0x32f1("0x31", "hHMm")',
        result: 'qqS',
    },
    {
        firstArg: '0x32',
        secondArg: 'tmku',
        script: '_0x32f1("0x32", "tmku")',
        result: 'qRH',
    },
    {
        firstArg: '0x33',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x33", "SB@Q")',
        result: 'bRK',
    },
    {
        firstArg: '0x34',
        secondArg: '4!X[',
        script: '_0x32f1("0x34", "4!X[")',
        result: 'Jud',
    },
    {
        firstArg: '0x35',
        secondArg: 'e3R0',
        script: '_0x32f1("0x35", "e3R0")',
        result: 'bRK',
    },
    {
        firstArg: '0x36',
        secondArg: 'hAPU',
        script: '_0x32f1("0x36", "hAPU")',
        result: 'zMG',
    },
    {
        firstArg: '0x37',
        secondArg: 'V%v2',
        script: '_0x32f1("0x37", "V%v2")',
        result: '4|5|1|0|3|2',
    },
    {
        firstArg: '0x38',
        secondArg: 'C)%p',
        script: '_0x32f1("0x38", "C)%p")',
        result: 'split',
    },
    {
        firstArg: '0x39',
        secondArg: 'RCFI',
        script: '_0x32f1("0x39", "RCFI")',
        result: 'XKm',
    },
    {
        firstArg: '0x3a',
        secondArg: 'fo7J',
        script: '_0x32f1("0x3a", "fo7J")',
        result: 'length',
    },
    {
        firstArg: '0x3b',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x3b", "SB@Q")',
        result: 'substr',
    },
    {
        firstArg: '0x3c',
        secondArg: '^h6e',
        script: '_0x32f1("0x3c", "^h6e")',
        result: 'indexOf',
    },
    {
        firstArg: '0x3d',
        secondArg: '6)P!',
        script: '_0x32f1("0x3d", "6)P!")',
        result: 'substr',
    },
    {
        firstArg: '0x3e',
        secondArg: 'plp9',
        script: '_0x32f1("0x3e", "plp9")',
        result: 'ITV',
    },
    {
        firstArg: '0x3f',
        secondArg: 'PVM9',
        script: '_0x32f1("0x3f", "PVM9")',
        result: 'indexOf',
    },
    {
        firstArg: '0x40',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x40", "Y(gg")',
        result: 'length',
    },
    {
        firstArg: '0x41',
        secondArg: '^h6e',
        script: '_0x32f1("0x41", "^h6e")',
        result: 'test',
    },
    {
        firstArg: '0x42',
        secondArg: 'hHMm',
        script: '_0x32f1("0x42", "hHMm")',
        result: 'length',
    },
    {
        firstArg: '0x43',
        secondArg: 'ieO2',
        script: '_0x32f1("0x43", "ieO2")',
        result: 'cookie',
    },
    {
        firstArg: '0x44',
        secondArg: 'QA4[',
        script: '_0x32f1("0x44", "QA4[")',
        result: 'split',
    },
    {
        firstArg: '0x45',
        secondArg: 'QA4[',
        script: '_0x32f1("0x45", "QA4[")',
        result: 'dxS',
    },
    {
        firstArg: '0x46',
        secondArg: 'C)%p',
        script: '_0x32f1("0x46", "C)%p")',
        result: 'Array',
    },
    {
        firstArg: '0x47',
        secondArg: 'fjzy',
        script: '_0x32f1("0x47", "fjzy")',
        result: 'RegExp',
    },
    {
        firstArg: '0x48',
        secondArg: 'lZot',
        script: '_0x32f1("0x48", "lZot")',
        result: '^\\s?incap_ses_',
    },
    {
        firstArg: '0x49',
        secondArg: 'D6b8',
        script: '_0x32f1("0x49", "D6b8")',
        result: '14|11|10|7|17|4|15|2|13|9|5|0|6|12|8|3|1|18|16',
    },
    {
        firstArg: '0x4a',
        secondArg: 'fo7J',
        script: '_0x32f1("0x4a", "fo7J")',
        result: 'split',
    },
    {
        firstArg: '0x4b',
        secondArg: 'ErAG',
        script: '_0x32f1("0x4b", "ErAG")',
        result: 'join',
    },
    {
        firstArg: '0x4c',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x4c", "SB@Q")',
        result: 'wOB',
    },
    {
        firstArg: '0x4d',
        secondArg: '4hK1',
        script: '_0x32f1("0x4d", "4hK1")',
        result: 'Pjf',
    },
    {
        firstArg: '0x4e',
        secondArg: 'EECj',
        script: '_0x32f1("0x4e", "EECj")',
        result: 'CRV',
    },
    {
        firstArg: '0x4f',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x4f", "lJ]t")',
        result: 'CRV',
    },
    {
        firstArg: '0x50',
        secondArg: ']uNf',
        script: '_0x32f1("0x50", "]uNf")',
        result: 'CRV',
    },
    {
        firstArg: '0x51',
        secondArg: 'lZot',
        script: '_0x32f1("0x51", "lZot")',
        result: 'Acf',
    },
    {
        firstArg: '0x52',
        secondArg: 'OzL2',
        script: '_0x32f1("0x52", "OzL2")',
        result: 'dcw',
    },
    {
        firstArg: '0x53',
        secondArg: 'RCFI',
        script: '_0x32f1("0x53", "RCFI")',
        result: 'length',
    },
    {
        firstArg: '0x54',
        secondArg: 'D6b8',
        script: '_0x32f1("0x54", "D6b8")',
        result: 'substr',
    },
    {
        firstArg: '0x55',
        secondArg: '4hK1',
        script: '_0x32f1("0x55", "4hK1")',
        result: ',digest=',
    },
    {
        firstArg: '0x56',
        secondArg: 'ErAG',
        script: '_0x32f1("0x56", "ErAG")',
        result: ',s=',
    },
    {
        firstArg: '0x57',
        secondArg: 'plp9',
        script: '_0x32f1("0x57", "plp9")',
        result: 'push',
    },
    {
        firstArg: '0x58',
        secondArg: 'C)%p',
        script: '_0x32f1("0x58", "C)%p")',
        result: 'gjR',
    },
    {
        firstArg: '0x59',
        secondArg: 'Y)S$',
        script: '_0x32f1("0x59", "Y)S$")',
        result: '77+9Ru+/vRDvv70E1rcq77+9azTvv73vv70077+9',
    },
    {
        firstArg: '0x5b',
        secondArg: 'M6RB',
        script: '_0x32f1("0x5b", "M6RB")',
        result: 'lQy',
    },
    {
        firstArg: '0x5c',
        secondArg: 'fjzy',
        script: '_0x32f1("0x5c", "fjzy")',
        result: 'length',
    },
    {
        firstArg: '0x5d',
        secondArg: ']ecs',
        script: '_0x32f1("0x5d", "]ecs")',
        result: 'CRV',
    },
    {
        firstArg: '0x5e',
        secondArg: '6)P!',
        script: '_0x32f1("0x5e", "6)P!")',
        result: 'Kvh',
    },
    {
        firstArg: '0x5f',
        secondArg: 'tmku',
        script: '_0x32f1("0x5f", "tmku")',
        result: 'lQy',
    },
    {
        firstArg: '0xd',
        secondArg: 'E[@b',
        script: '_0x32f1("0xd", "E[@b")',
        result: 'length',
    },
    {
        firstArg: '0x60',
        secondArg: 'Kax[',
        script: '_0x32f1("0x60", "Kax[")',
        result: 'Array',
    },
    {
        firstArg: '0x61',
        secondArg: 'EECj',
        script: '_0x32f1("0x61", "EECj")',
        result: 'length',
    },
    {
        firstArg: '0x62',
        secondArg: 'orkc',
        script: '_0x32f1("0x62", "orkc")',
        result: 'Kvh',
    },
    {
        firstArg: '0x63',
        secondArg: 'wSBw',
        script: '_0x32f1("0x63", "wSBw")',
        result: 'lQy',
    },
    {
        firstArg: '0x5c',
        secondArg: 'fjzy',
        script: '_0x32f1("0x5c", "fjzy")',
        result: 'length',
    },
    {
        firstArg: '0x64',
        secondArg: '6)P!',
        script: '_0x32f1("0x64", "6)P!")',
        result: 'HnL',
    },
    {
        firstArg: '0x65',
        secondArg: '4hK1',
        script: '_0x32f1("0x65", "4hK1")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x66',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x66", "K]Ws")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x67',
        secondArg: '4hK1',
        script: '_0x32f1("0x67", "4hK1")',
        result: 'length',
    },
    {
        firstArg: '0x68',
        secondArg: '^h6e',
        script: '_0x32f1("0x68", "^h6e")',
        result: 'toString',
    },
    {
        firstArg: '0x69',
        secondArg: 'OzL2',
        script: '_0x32f1("0x69", "OzL2")',
        result: 'aRv',
    },
    {
        firstArg: '0x6a',
        secondArg: '4!X[',
        script: '_0x32f1("0x6a", "4!X[")',
        result: 'Bgu',
    },
    {
        firstArg: '0x6b',
        secondArg: 'PVM9',
        script: '_0x32f1("0x6b", "PVM9")',
        result: '___utmvc',
    },
    {
        firstArg: '0x6c',
        secondArg: 'plp9',
        script: '_0x32f1("0x6c", "plp9")',
        result: 'DDl',
    },
    {
        firstArg: '0x6d',
        secondArg: 'eSAb',
        script: '_0x32f1("0x6d", "eSAb")',
        result: 'pop',
    },
    {
        firstArg: '0x6e',
        secondArg: '0MG!',
        script: '_0x32f1("0x6e", "0MG!")',
        result: 'Zac',
    },
    {
        firstArg: '0x6f',
        secondArg: 'PVM9',
        script: '_0x32f1("0x6f", "PVM9")',
        result: 'length',
    },
    {
        firstArg: '0x70',
        secondArg: 'orkc',
        script: '_0x32f1("0x70", "orkc")',
        result: 'charCodeAt',
    },
    {
        firstArg: '0x71',
        secondArg: 'C)%p',
        script: '_0x32f1("0x71", "C)%p")',
        result: 'SPp',
    },
    {
        firstArg: '0x72',
        secondArg: 'orkc',
        script: '_0x32f1("0x72", "orkc")',
        result: '2|5|4|1|3|0',
    },
    {
        firstArg: '0x73',
        secondArg: ']ecs',
        script: '_0x32f1("0x73", "]ecs")',
        result: 'split',
    },
    {
        firstArg: '0x43',
        secondArg: 'ieO2',
        script: '_0x32f1("0x43", "ieO2")',
        result: 'cookie',
    },
    {
        firstArg: '0x74',
        secondArg: 'EECj',
        script: '_0x32f1("0x74", "EECj")',
        result: 'vxj',
    },
    {
        firstArg: '0x75',
        secondArg: 'orkc',
        script: '_0x32f1("0x75", "orkc")',
        result: 'TNP',
    },
    {
        firstArg: '0x76',
        secondArg: 'OzL2',
        script: '_0x32f1("0x76", "OzL2")',
        result: 'qyw',
    },
    {
        firstArg: '0x77',
        secondArg: '6V&2',
        script: '_0x32f1("0x77", "6V&2")',
        result: '; path=/',
    },
    {
        firstArg: '0x78',
        secondArg: 'wSBw',
        script: '_0x32f1("0x78", "wSBw")',
        result: 'substr',
    },
    {
        firstArg: '0x79',
        secondArg: 'plp9',
        script: '_0x32f1("0x79", "plp9")',
        result: 'Date',
    },
    {
        firstArg: '0x7a',
        secondArg: 'V%v2',
        script: '_0x32f1("0x7a", "V%v2")',
        result: 'setTime',
    },
    {
        firstArg: '0x7b',
        secondArg: '&%YX',
        script: '_0x32f1("0x7b", "&%YX")',
        result: 'qyw',
    },
    {
        firstArg: '0x7c',
        secondArg: 'M6RB',
        script: '_0x32f1("0x7c", "M6RB")',
        result: 'getTime',
    },
    {
        firstArg: '0x7d',
        secondArg: 'C)%p',
        script: '_0x32f1("0x7d", "C)%p")',
        result: 'Ekx',
    },
    {
        firstArg: '0x7e',
        secondArg: 'D6b8',
        script: '_0x32f1("0x7e", "D6b8")',
        result: 'GtD',
    },
    {
        firstArg: '0x7f',
        secondArg: 'lZot',
        script: '_0x32f1("0x7f", "lZot")',
        result: '; expires=',
    },
    {
        firstArg: '0x80',
        secondArg: 'EECj',
        script: '_0x32f1("0x80", "EECj")',
        result: 'toGMTString',
    },
    {
        firstArg: '0x81',
        secondArg: ']ecs',
        script: '_0x32f1("0x81", "]ecs")',
        result: 'substr',
    },
    {
        firstArg: '0x82',
        secondArg: '0MG!',
        script: '_0x32f1("0x82", "0MG!")',
        result: '77+9cMyw77+977+977+9NXLvv73vv73vv73vv71T',
    },
    {
        firstArg: '0x83',
        secondArg: '6)P!',
        script: '_0x32f1("0x83", "6)P!")',
        result: 'rGl',
    },
    {
        firstArg: '0x84',
        secondArg: '&%YX',
        script: '_0x32f1("0x84", "&%YX")',
        result: 'cYX',
    },
    {
        firstArg: '0x85',
        secondArg: 'nWG6',
        script: '_0x32f1("0x85", "nWG6")',
        result: 'Xir',
    },
    {
        firstArg: '0x86',
        secondArg: '*BCO',
        script: '_0x32f1("0x86", "*BCO")',
        result: 'QcP',
    },
    {
        firstArg: '0x87',
        secondArg: 'TER%',
        script: '_0x32f1("0x87", "TER%")',
        result: 'OpM',
    },
    {
        firstArg: '0x88',
        secondArg: 'QA4[',
        script: '_0x32f1("0x88", "QA4[")',
        result: 'OmJ',
    },
    {
        firstArg: '0x89',
        secondArg: 'eSAb',
        script: '_0x32f1("0x89", "eSAb")',
        result: 'RjV',
    },
    {
        firstArg: '0x8a',
        secondArg: 'hHMm',
        script: '_0x32f1("0x8a", "hHMm")',
        result: 'eYX',
    },
    {
        firstArg: '0x8b',
        secondArg: 'QA4[',
        script: '_0x32f1("0x8b", "QA4[")',
        result: 'length',
    },
    {
        firstArg: '0x8c',
        secondArg: 'hHMm',
        script: '_0x32f1("0x8c", "hHMm")',
        result: 'UMe',
    },
    {
        firstArg: '0x8d',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x8d", "Y(gg")',
        result: 'constructor',
    },
    {
        firstArg: '0x8e',
        secondArg: '4!X[',
        script: '_0x32f1("0x8e", "4!X[")',
        result: 'debugger',
    },
    {
        firstArg: '0x8f',
        secondArg: 'wSBw',
        script: '_0x32f1("0x8f", "wSBw")',
        result: 'constructor',
    },
    {
        firstArg: '0x90',
        secondArg: 'fjzy',
        script: '_0x32f1("0x90", "fjzy")',
        result: 'debugger',
    },
    {
        firstArg: '0x91',
        secondArg: 'OzL2',
        script: '_0x32f1("0x91", "OzL2")',
        result: 'QeU',
    },
    {
        firstArg: '0x92',
        secondArg: 'Kax[',
        script: '_0x32f1("0x92", "Kax[")',
        result: 'oOh',
    },
    {
        firstArg: '0x93',
        secondArg: 'OzL2',
        script: '_0x32f1("0x93", "OzL2")',
        result: 'XeK',
    },
    {
        firstArg: '0x94',
        secondArg: 'PVM9',
        script: '_0x32f1("0x94", "PVM9")',
        result: 'VUE',
    },
    {
        firstArg: '0x95',
        secondArg: 'ErAG',
        script: '_0x32f1("0x95", "ErAG")',
        result: 'Date',
    },
    {
        firstArg: '0x96',
        secondArg: 'qMq4',
        script: '_0x32f1("0x96", "qMq4")',
        result: 'getTime',
    },
    {
        firstArg: '0x97',
        secondArg: 'lZot',
        script: '_0x32f1("0x97", "lZot")',
        result: 'qvi',
    },
    {
        firstArg: '0x98',
        secondArg: 'V%v2',
        script: '_0x32f1("0x98", "V%v2")',
        result: '3|0|1|5|8|2|4|7|6',
    },
    {
        firstArg: '0x99',
        secondArg: ']Y49',
        script: '_0x32f1("0x99", "]Y49")',
        result: 'split',
    },
    {
        firstArg: '0x9a',
        secondArg: 'y1KF',
        script: '_0x32f1("0x9a", "y1KF")',
        result: '77+977+9cD41Ye+/ve+/vS5bQO+/ve+/ve+/vV8j',
    },
    {
        firstArg: '0x9b',
        secondArg: 'e3R0',
        script: '_0x32f1("0x9b", "e3R0")',
        result: 'Dyn',
    },
    {
        firstArg: '0x9c',
        secondArg: 'ErAG',
        script: '_0x32f1("0x9c", "ErAG")',
        result: 'length',
    },
    {
        firstArg: '0x9d',
        secondArg: 'y1KF',
        script: '_0x32f1("0x9d", "y1KF")',
        result: 'join',
    },
    {
        firstArg: '0x9e',
        secondArg: 'OzL2',
        script: '_0x32f1("0x9e", "OzL2")',
        result: 'PxZ',
    },
    {
        firstArg: '0xd',
        secondArg: 'E[@b',
        script: '_0x32f1("0xd", "E[@b")',
        result: 'length',
    },
    {
        firstArg: '0x9f',
        secondArg: 'e3R0',
        script: '_0x32f1("0x9f", "e3R0")',
        result: 'exists',
    },
    {
        firstArg: '0xa0',
        secondArg: ']ecs',
        script: '_0x32f1("0xa0", "]ecs")',
        result: 'ILA',
    },
    {
        firstArg: '0xa1',
        secondArg: 'wSBw',
        script: '_0x32f1("0xa1", "wSBw")',
        result: 'VKc',
    },
    {
        firstArg: '0xa2',
        secondArg: '6)P!',
        script: '_0x32f1("0xa2", "6)P!")',
        result: 'undefined',
    },
    {
        firstArg: '0xd',
        secondArg: 'E[@b',
        script: '_0x32f1("0xd", "E[@b")',
        result: 'length',
    },
    {
        firstArg: '0xa3',
        secondArg: '&9]!',
        script: '_0x32f1("0xa3", "&9]!")',
        result: 'Qfv',
    },
    {
        firstArg: '0xa4',
        secondArg: 'orkc',
        script: '_0x32f1("0xa4", "orkc")',
        result: '=true',
    },
    {
        firstArg: '0xa5',
        secondArg: 'qMq4',
        script: '_0x32f1("0xa5", "qMq4")',
        result: 'length',
    },
    {
        firstArg: '0xa6',
        secondArg: 'E[@b',
        script: '_0x32f1("0xa6", "E[@b")',
        result: 'tcD',
    },
    {
        firstArg: '0xa7',
        secondArg: '0MG!',
        script: '_0x32f1("0xa7", "0MG!")',
        result: '=false',
    },
    {
        firstArg: '0x6f',
        secondArg: 'PVM9',
        script: '_0x32f1("0x6f", "PVM9")',
        result: 'length',
    },
    {
        firstArg: '0xa8',
        secondArg: '6)P!',
        script: '_0x32f1("0xa8", "6)P!")',
        result: 'WDU',
    },
    {
        firstArg: '0xa9',
        secondArg: 'TER%',
        script: '_0x32f1("0xa9", "TER%")',
        result: '=false',
    },
    {
        firstArg: '0xaa',
        secondArg: 'K]Ws',
        script: '_0x32f1("0xaa", "K]Ws")',
        result: 'value',
    },
    {
        firstArg: '0xab',
        secondArg: 'orkc',
        script: '_0x32f1("0xab", "orkc")',
        result: 'rPn',
    },
    {
        firstArg: '0xac',
        secondArg: '6)P!',
        script: '_0x32f1("0xac", "6)P!")',
        result: 'JiU',
    },
    {
        firstArg: '0xad',
        secondArg: '^h6e',
        script: '_0x32f1("0xad", "^h6e")',
        result: 'undefined',
    },
    {
        firstArg: '0x8b',
        secondArg: 'QA4[',
        script: '_0x32f1("0x8b", "QA4[")',
        result: 'length',
    },
    {
        firstArg: '0xae',
        secondArg: '4hK1',
        script: '_0x32f1("0xae", "4hK1")',
        result: 'WDU',
    },
    {
        firstArg: '0xaf',
        secondArg: 'ErAG',
        script: '_0x32f1("0xaf", "ErAG")',
        result: 'tcD',
    },
    {
        firstArg: '0xb0',
        secondArg: 'lZot',
        script: '_0x32f1("0xb0", "lZot")',
        result: '=undefined',
    },
    {
        firstArg: '0xb1',
        secondArg: 'fjzy',
        script: '_0x32f1("0xb1", "fjzy")',
        result: 'JiU',
    },
    {
        firstArg: '0x9c',
        secondArg: 'ErAG',
        script: '_0x32f1("0x9c", "ErAG")',
        result: 'length',
    },
    {
        firstArg: '0xb2',
        secondArg: 'B^5n',
        script: '_0x32f1("0xb2", "B^5n")',
        result: 'rVm',
    },
    {
        firstArg: '0xb3',
        secondArg: '0MG!',
        script: '_0x32f1("0xb3", "0MG!")',
        result: 'TDl',
    },
    {
        firstArg: '0xb4',
        secondArg: 'Qv[c',
        script: '_0x32f1("0xb4", "Qv[c")',
        result: '=null',
    },
    {
        firstArg: '0xb5',
        secondArg: 'Y)S$',
        script: '_0x32f1("0xb5", "Y)S$")',
        result: 'length',
    },
    {
        firstArg: '0xb6',
        secondArg: 'OzL2',
        script: '_0x32f1("0xb6", "OzL2")',
        result: 'yDO',
    },
    {
        firstArg: '0xb7',
        secondArg: '6)P!',
        script: '_0x32f1("0xb7", "6)P!")',
        result: 'TDl',
    },
    {
        firstArg: '0xb8',
        secondArg: 'V%v2',
        script: '_0x32f1("0xb8", "V%v2")',
        result: 'TDl',
    },
    {
        firstArg: '0xb9',
        secondArg: 'orkc',
        script: '_0x32f1("0xb9", "orkc")',
        result: 'toString',
    },
    {
        firstArg: '0x40',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x40", "Y(gg")',
        result: 'length',
    },
    {
        firstArg: '0xba',
        secondArg: 'orkc',
        script: '_0x32f1("0xba", "orkc")',
        result: 'TDl',
    },
    {
        firstArg: '0xbb',
        secondArg: '@p]j',
        script: '_0x32f1("0xbb", "@p]j")',
        result: '=cannot evaluate',
    },
    {
        firstArg: '0xbc',
        secondArg: 'tmku',
        script: '_0x32f1("0xbc", "tmku")',
        result: 'length',
    },
    {
        firstArg: '0xbd',
        secondArg: '4!X[',
        script: '_0x32f1("0xbd", "4!X[")',
        result: 'hfj',
    },
    {
        firstArg: '0xbe',
        secondArg: '*BCO',
        script: '_0x32f1("0xbe", "*BCO")',
        result: 'TDl',
    },
    {
        firstArg: '0xbf',
        secondArg: ']Y49',
        script: '_0x32f1("0xbf", "]Y49")',
        result: 'VcZ',
    },
    {
        firstArg: '0xc0',
        secondArg: '&9]!',
        script: '_0x32f1("0xc0", "&9]!")',
        result: 'plugin_extentions',
    },
    {
        firstArg: '0xc1',
        secondArg: 'fjzy',
        script: '_0x32f1("0xc1", "fjzy")',
        result: '3|2|1|0|4',
    },
    {
        firstArg: '0xc2',
        secondArg: 'V%v2',
        script: '_0x32f1("0xc2", "V%v2")',
        result: 'split',
    },
    {
        firstArg: '0xc3',
        secondArg: 'nWG6',
        script: '_0x32f1("0xc3", "nWG6")',
        result: 'EKK',
    },
    {
        firstArg: '0xc4',
        secondArg: 'fjzy',
        script: '_0x32f1("0xc4", "fjzy")',
        result: 'plugins',
    },
    {
        firstArg: '0xc5',
        secondArg: 'e3R0',
        script: '_0x32f1("0xc5", "e3R0")',
        result: 'length',
    },
    {
        firstArg: '0xc6',
        secondArg: 'M6RB',
        script: '_0x32f1("0xc6", "M6RB")',
        result: '3|4|1|2|0',
    },
    {
        firstArg: '0xc7',
        secondArg: 'Kx0j',
        script: '_0x32f1("0xc7", "Kx0j")',
        result: 'split',
    },
    {
        firstArg: '0xc8',
        secondArg: 'qMq4',
        script: '_0x32f1("0xc8", "qMq4")',
        result: 'ZoX',
    },
    {
        firstArg: '0xc9',
        secondArg: '4!X[',
        script: '_0x32f1("0xc9", "4!X[")',
        result: 'indexOf',
    },
    {
        firstArg: '0xca',
        secondArg: 'K]Ws',
        script: '_0x32f1("0xca", "K]Ws")',
        result: 'push',
    },
    {
        firstArg: '0xcb',
        secondArg: 'hAPU',
        script: '_0x32f1("0xcb", "hAPU")',
        result: 'no extention',
    },
    {
        firstArg: '0xcc',
        secondArg: 'E[@b',
        script: '_0x32f1("0xcc", "E[@b")',
        result: 'JiU',
    },
    {
        firstArg: '0xcd',
        secondArg: '9xgR',
        script: '_0x32f1("0xcd", "9xgR")',
        result: 'undefined',
    },
    {
        firstArg: '0xce',
        secondArg: 'e3R0',
        script: '_0x32f1("0xce", "e3R0")',
        result: 'filename is undefined',
    },
    {
        firstArg: '0xcf',
        secondArg: 'OzL2',
        script: '_0x32f1("0xcf", "OzL2")',
        result: 'SNZ',
    },
    {
        firstArg: '0xd0',
        secondArg: 'orkc',
        script: '_0x32f1("0xd0", "orkc")',
        result: 'split',
    },
    {
        firstArg: '0xd1',
        secondArg: 'Kax[',
        script: '_0x32f1("0xd1", "Kax[")',
        result: 'length',
    },
    {
        firstArg: '0xd2',
        secondArg: 'eSAb',
        script: '_0x32f1("0xd2", "eSAb")',
        result: 'split',
    },
    {
        firstArg: '0xd3',
        secondArg: 'hAPU',
        script: '_0x32f1("0xd3", "hAPU")',
        result: 'pop',
    },
    {
        firstArg: '0xd4',
        secondArg: 'hAPU',
        script: '_0x32f1("0xd4", "hAPU")',
        result: 'JiU',
    },
    {
        firstArg: '0xd5',
        secondArg: ']Y49',
        script: '_0x32f1("0xd5", "]Y49")',
        result: 'plugins',
    },
    {
        firstArg: '0xd6',
        secondArg: 'wSBw',
        script: '_0x32f1("0xd6", "wSBw")',
        result: 'undefined',
    },
    {
        firstArg: '0x6f',
        secondArg: 'PVM9',
        script: '_0x32f1("0x6f", "PVM9")',
        result: 'length',
    },
    {
        firstArg: '0xd7',
        secondArg: 'hAPU',
        script: '_0x32f1("0xd7", "hAPU")',
        result: 'pxH',
    },
    {
        firstArg: '0xd8',
        secondArg: '^h6e',
        script: '_0x32f1("0xd8", "^h6e")',
        result: 'plugin_ext=plugins[i] is undefined',
    },
    {
        firstArg: '0xd9',
        secondArg: '0MG!',
        script: '_0x32f1("0xd9", "0MG!")',
        result: 'plugins',
    },
    {
        firstArg: '0xda',
        secondArg: ']ecs',
        script: '_0x32f1("0xda", "]ecs")',
        result: 'filename',
    },
    {
        firstArg: '0xdb',
        secondArg: 'plp9',
        script: '_0x32f1("0xdb", "plp9")',
        result: 'plugins',
    },
    {
        firstArg: '0xdc',
        secondArg: 'C)%p',
        script: '_0x32f1("0xdc", "C)%p")',
        result: 'length',
    },
    {
        firstArg: '0xdd',
        secondArg: 'plp9',
        script: '_0x32f1("0xdd", "plp9")',
        result: 'nWx',
    },
    {
        firstArg: '0xde',
        secondArg: '4hK1',
        script: '_0x32f1("0xde", "4hK1")',
        result: 'nWx',
    },
    {
        firstArg: '0xc5',
        secondArg: 'e3R0',
        script: '_0x32f1("0xc5", "e3R0")',
        result: 'length',
    },
    {
        firstArg: '0xdf',
        secondArg: 'RCFI',
        script: '_0x32f1("0xdf", "RCFI")',
        result: 'plugin_ext=no plugins',
    },
    {
        firstArg: '0xe0',
        secondArg: 'K]Ws',
        script: '_0x32f1("0xe0", "K]Ws")',
        result: 'length',
    },
    {
        firstArg: '0xe1',
        secondArg: '@p]j',
        script: '_0x32f1("0xe1", "@p]j")',
        result: 'dnq',
    },
    {
        firstArg: '0xe2',
        secondArg: 'tmku',
        script: '_0x32f1("0xe2", "tmku")',
        result: 'plugin_ext=cannot evaluate',
    },
    {
        firstArg: '0xe3',
        secondArg: 'QA4[',
        script: '_0x32f1("0xe3", "QA4[")',
        result: 'indexOf',
    },
    {
        firstArg: '0xd1',
        secondArg: 'Kax[',
        script: '_0x32f1("0xd1", "Kax[")',
        result: 'length',
    },
    {
        firstArg: '0xe4',
        secondArg: 'plp9',
        script: '_0x32f1("0xe4", "plp9")',
        result: 'dnq',
    },
    {
        firstArg: '0xe5',
        secondArg: 'tmku',
        script: '_0x32f1("0xe5", "tmku")',
        result: 'plugin_ext=indexOf is not a function',
    },
    {
        firstArg: '0xe6',
        secondArg: 'TER%',
        script: '_0x32f1("0xe6", "TER%")',
        result: 'ycw',
    },
    {
        firstArg: '0xe7',
        secondArg: ']uNf',
        script: '_0x32f1("0xe7", "]uNf")',
        result: 'length',
    },
    {
        firstArg: '0xe8',
        secondArg: ']ecs',
        script: '_0x32f1("0xe8", "]ecs")',
        result: 'length',
    },
    {
        firstArg: '0xe9',
        secondArg: 'lJ]t',
        script: '_0x32f1("0xe9", "lJ]t")',
        result: 'dnq',
    },
    {
        firstArg: '0xea',
        secondArg: 'Kx0j',
        script: '_0x32f1("0xea", "Kx0j")',
        result: 'VcZ',
    },
    {
        firstArg: '0xeb',
        secondArg: 'qMq4',
        script: '_0x32f1("0xeb", "qMq4")',
        result: 'plugin_ext=',
    },
    {
        firstArg: '0xec',
        secondArg: 'TER%',
        script: '_0x32f1("0xec", "TER%")',
        result: 'length',
    },
    {
        firstArg: '0xed',
        secondArg: '4!X[',
        script: '_0x32f1("0xed", "4!X[")',
        result: 'dnq',
    },
    {
        firstArg: '0xee',
        secondArg: '^h6e',
        script: '_0x32f1("0xee", "^h6e")',
        result: 'VcZ',
    },
    {
        firstArg: '0xef',
        secondArg: 'plp9',
        script: '_0x32f1("0xef", "plp9")',
        result: 'plugin_ext=',
    },
    {
        firstArg: '0xf0',
        secondArg: 'Qv[c',
        script: '_0x32f1("0xf0", "Qv[c")',
        result: 'function',
    },
    {
        firstArg: '0xf1',
        secondArg: 'C)%p',
        script: '_0x32f1("0xf1", "C)%p")',
        result: 'JiU',
    },
    {
        firstArg: '0xf2',
        secondArg: 'eSAb',
        script: '_0x32f1("0xf2", "eSAb")',
        result: 'deviceType',
    },
    {
        firstArg: '0xf3',
        secondArg: 'plp9',
        script: '_0x32f1("0xf3", "plp9")',
        result: 'userAgent',
    },
    {
        firstArg: '0xf4',
        secondArg: 'EECj',
        script: '_0x32f1("0xf4", "EECj")',
        result: 'test',
    },
    {
        firstArg: '0xf5',
        secondArg: 'lJ]t',
        script: '_0x32f1("0xf5", "lJ]t")',
        result: 'tablet',
    },
    {
        firstArg: '0xf6',
        secondArg: 'Kax[',
        script: '_0x32f1("0xf6", "Kax[")',
        result: 'test',
    },
    {
        firstArg: '0xf7',
        secondArg: 'fo7J',
        script: '_0x32f1("0xf7", "fo7J")',
        result: 'mobile',
    },
    {
        firstArg: '0xf8',
        secondArg: '6V&2',
        script: '_0x32f1("0xf8", "6V&2")',
        result: 'desktop',
    },
    {
        firstArg: '0xd',
        secondArg: 'E[@b',
        script: '_0x32f1("0xd", "E[@b")',
        result: 'length',
    },
    {
        firstArg: '0xf9',
        secondArg: '&%YX',
        script: '_0x32f1("0xf9", "&%YX")',
        result: 'dnq',
    },
    {
        firstArg: '0xfa',
        secondArg: 'lJ]t',
        script: '_0x32f1("0xfa", "lJ]t")',
        result: 'VcZ',
    },
    {
        firstArg: '0xfb',
        secondArg: 'y1KF',
        script: '_0x32f1("0xfb", "y1KF")',
        result: 'nKP',
    },
    {
        firstArg: '0xfc',
        secondArg: 'nWG6',
        script: '_0x32f1("0xfc", "nWG6")',
        result: 'length',
    },
    {
        firstArg: '0xfd',
        secondArg: '9xgR',
        script: '_0x32f1("0xfd", "9xgR")',
        result: 'dnq',
    },
    {
        firstArg: '0xfe',
        secondArg: 'V%v2',
        script: '_0x32f1("0xfe", "V%v2")',
        result: 'wXf',
    },
    {
        firstArg: '0xff',
        secondArg: '4hK1',
        script: '_0x32f1("0xff", "4hK1")',
        result: 'uqg',
    },
    {
        firstArg: '0x100',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x100", "Y(gg")',
        result: '=cannot evaluate',
    },
    {
        firstArg: '0x101',
        secondArg: '&%YX',
        script: '_0x32f1("0x101", "&%YX")',
        result: 'toString',
    },
    {
        firstArg: '0x102',
        secondArg: 'E[@b',
        script: '_0x32f1("0x102", "E[@b")',
        result: 'rPn',
    },
    {
        firstArg: '0x103',
        secondArg: 'e3R0',
        script: '_0x32f1("0x103", "e3R0")',
        result: 'QfM',
    },
    {
        firstArg: '0x104',
        secondArg: '9xgR',
        script: '_0x32f1("0x104", "9xgR")',
        result: 'navigator',
    },
    {
        firstArg: '0x105',
        secondArg: 'RCFI',
        script: '_0x32f1("0x105", "RCFI")',
        result: 'exists',
    },
    {
        firstArg: '0x106',
        secondArg: '6)P!',
        script: '_0x32f1("0x106", "6)P!")',
        result: 'navigator.vendor',
    },
    {
        firstArg: '0x107',
        secondArg: '0MG!',
        script: '_0x32f1("0x107", "0MG!")',
        result: 'value',
    },
    {
        firstArg: '0x108',
        secondArg: 'C)%p',
        script: '_0x32f1("0x108", "C)%p")',
        result: 'vendor',
    },
    {
        firstArg: '0x109',
        secondArg: 'fo7J',
        script: '_0x32f1("0x109", "fo7J")',
        result: 'navigator.appName',
    },
    {
        firstArg: '0x10a',
        secondArg: 'fo7J',
        script: '_0x32f1("0x10a", "fo7J")',
        result: 'value',
    },
    {
        firstArg: '0x10b',
        secondArg: 'M6RB',
        script: '_0x32f1("0x10b", "M6RB")',
        result: 'appName',
    },
    {
        firstArg: '0x10c',
        secondArg: 'tmku',
        script: '_0x32f1("0x10c", "tmku")',
        result: 'navigator.plugins.length==0',
    },
    {
        firstArg: '0x10d',
        secondArg: '9xgR',
        script: '_0x32f1("0x10d", "9xgR")',
        result: 'value',
    },
    {
        firstArg: '0x10e',
        secondArg: 'EECj',
        script: '_0x32f1("0x10e", "EECj")',
        result: 'nCj',
    },
    {
        firstArg: '0x10f',
        secondArg: 'fo7J',
        script: '_0x32f1("0x10f", "fo7J")',
        result: 'plugins',
    },
    {
        firstArg: '0x61',
        secondArg: 'EECj',
        script: '_0x32f1("0x61", "EECj")',
        result: 'length',
    },
    {
        firstArg: '0x110',
        secondArg: '&%YX',
        script: '_0x32f1("0x110", "&%YX")',
        result: 'navigator.platform',
    },
    {
        firstArg: '0x111',
        secondArg: 'hHMm',
        script: '_0x32f1("0x111", "hHMm")',
        result: 'value',
    },
    {
        firstArg: '0x112',
        secondArg: ']ecs',
        script: '_0x32f1("0x112", "]ecs")',
        result: 'platform',
    },
    {
        firstArg: '0x113',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x113", "SB@Q")',
        result: 'navigator.webdriver',
    },
    {
        firstArg: '0x114',
        secondArg: ']uNf',
        script: '_0x32f1("0x114", "]uNf")',
        result: 'value',
    },
    {
        firstArg: '0x115',
        secondArg: 'M6RB',
        script: '_0x32f1("0x115", "M6RB")',
        result: 'webdriver',
    },
    {
        firstArg: '0x116',
        secondArg: 'PVM9',
        script: '_0x32f1("0x116", "PVM9")',
        result: 'platform',
    },
    {
        firstArg: '0x117',
        secondArg: 'wSBw',
        script: '_0x32f1("0x117", "wSBw")',
        result: 'plugin_extentions',
    },
    {
        firstArg: '0x118',
        secondArg: '9xgR',
        script: '_0x32f1("0x118", "9xgR")',
        result: 'ActiveXObject',
    },
    {
        firstArg: '0x119',
        secondArg: 'OzL2',
        script: '_0x32f1("0x119", "OzL2")',
        result: 'exists',
    },
    {
        firstArg: '0x11a',
        secondArg: ']Y49',
        script: '_0x32f1("0x11a", "]Y49")',
        result: 'webkitURL',
    },
    {
        firstArg: '0x11b',
        secondArg: '0MG!',
        script: '_0x32f1("0x11b", "0MG!")',
        result: 'exists',
    },
    {
        firstArg: '0x11c',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x11c", "lJ]t")',
        result: '_phantom',
    },
    {
        firstArg: '0x11d',
        secondArg: '&%YX',
        script: '_0x32f1("0x11d", "&%YX")',
        result: 'exists',
    },
    {
        firstArg: '0x11e',
        secondArg: '*BCO',
        script: '_0x32f1("0x11e", "*BCO")',
        result: 'callPhantom',
    },
    {
        firstArg: '0x11f',
        secondArg: 'B^5n',
        script: '_0x32f1("0x11f", "B^5n")',
        result: 'exists',
    },
    {
        firstArg: '0x120',
        secondArg: '@p]j',
        script: '_0x32f1("0x120", "@p]j")',
        result: 'chrome',
    },
    {
        firstArg: '0x121',
        secondArg: 'D6b8',
        script: '_0x32f1("0x121", "D6b8")',
        result: 'exists',
    },
    {
        firstArg: '0x122',
        secondArg: 'wSBw',
        script: '_0x32f1("0x122", "wSBw")',
        result: 'yandex',
    },
    {
        firstArg: '0x123',
        secondArg: 'wSBw',
        script: '_0x32f1("0x123", "wSBw")',
        result: 'exists',
    },
    {
        firstArg: '0x124',
        secondArg: 'fjzy',
        script: '_0x32f1("0x124", "fjzy")',
        result: 'opera',
    },
    {
        firstArg: '0x125',
        secondArg: '@p]j',
        script: '_0x32f1("0x125", "@p]j")',
        result: 'exists',
    },
    {
        firstArg: '0x126',
        secondArg: 'plp9',
        script: '_0x32f1("0x126", "plp9")',
        result: 'opr',
    },
    {
        firstArg: '0x127',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x127", "lJ]t")',
        result: 'exists',
    },
    {
        firstArg: '0x128',
        secondArg: 'ErAG',
        script: '_0x32f1("0x128", "ErAG")',
        result: 'safari',
    },
    {
        firstArg: '0x129',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x129", "SB@Q")',
        result: 'exists',
    },
    {
        firstArg: '0x12a',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x12a", "SB@Q")',
        result: 'awesomium',
    },
    {
        firstArg: '0x12b',
        secondArg: '6V&2',
        script: '_0x32f1("0x12b", "6V&2")',
        result: 'exists',
    },
    {
        firstArg: '0x12c',
        secondArg: 'wSBw',
        script: '_0x32f1("0x12c", "wSBw")',
        result: 'puffinDevice',
    },
    {
        firstArg: '0x12d',
        secondArg: '9xgR',
        script: '_0x32f1("0x12d", "9xgR")',
        result: 'exists',
    },
    {
        firstArg: '0x12e',
        secondArg: 'M6RB',
        script: '_0x32f1("0x12e", "M6RB")',
        result: '__nightmare',
    },
    {
        firstArg: '0x11d',
        secondArg: '&%YX',
        script: '_0x32f1("0x11d", "&%YX")',
        result: 'exists',
    },
    {
        firstArg: '0x12f',
        secondArg: 'lZot',
        script: '_0x32f1("0x12f", "lZot")',
        result: 'domAutomation',
    },
    {
        firstArg: '0x130',
        secondArg: ']uNf',
        script: '_0x32f1("0x130", "]uNf")',
        result: 'exists',
    },
    {
        firstArg: '0x131',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x131", "lJ]t")',
        result: 'domAutomationController',
    },
    {
        firstArg: '0x11f',
        secondArg: 'B^5n',
        script: '_0x32f1("0x11f", "B^5n")',
        result: 'exists',
    },
    {
        firstArg: '0x132',
        secondArg: 'Kax[',
        script: '_0x32f1("0x132", "Kax[")',
        result: '_Selenium_IDE_Recorder',
    },
    {
        firstArg: '0x133',
        secondArg: 'Kx0j',
        script: '_0x32f1("0x133", "Kx0j")',
        result: 'exists',
    },
    {
        firstArg: '0x134',
        secondArg: 'plp9',
        script: '_0x32f1("0x134", "plp9")',
        result: 'document.__webdriver_script_fn',
    },
    {
        firstArg: '0x9f',
        secondArg: 'e3R0',
        script: '_0x32f1("0x9f", "e3R0")',
        result: 'exists',
    },
    {
        firstArg: '0x135',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x135", "lJ]t")',
        result: '__webdriver_script_fn',
    },
    {
        firstArg: '0x136',
        secondArg: ']Y49',
        script: '_0x32f1("0x136", "]Y49")',
        result: 'document.$cdc_asdjflasutopfhvcZLmcfl_',
    },
    {
        firstArg: '0x121',
        secondArg: 'D6b8',
        script: '_0x32f1("0x121", "D6b8")',
        result: 'exists',
    },
    {
        firstArg: '0x137',
        secondArg: 'RCFI',
        script: '_0x32f1("0x137", "RCFI")',
        result: '$cdc_asdjflasutopfhvcZLmcfl_',
    },
    {
        firstArg: '0x138',
        secondArg: '&%YX',
        script: '_0x32f1("0x138", "&%YX")',
        result: 'process.version',
    },
    {
        firstArg: '0x139',
        secondArg: 'nWG6',
        script: '_0x32f1("0x139", "nWG6")',
        result: 'exists',
    },
    {
        firstArg: '0x13a',
        secondArg: 'PVM9',
        script: '_0x32f1("0x13a", "PVM9")',
        result: 'version',
    },
    {
        firstArg: '0x13b',
        secondArg: '&%YX',
        script: '_0x32f1("0x13b", "&%YX")',
        result: 'global.require',
    },
    {
        firstArg: '0x13c',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x13c", "Y(gg")',
        result: 'exists',
    },
    {
        firstArg: '0x13d',
        secondArg: '&%YX',
        script: '_0x32f1("0x13d", "&%YX")',
        result: 'require',
    },
    {
        firstArg: '0x13e',
        secondArg: 'plp9',
        script: '_0x32f1("0x13e", "plp9")',
        result: 'global.process',
    },
    {
        firstArg: '0x11b',
        secondArg: '0MG!',
        script: '_0x32f1("0x11b", "0MG!")',
        result: 'exists',
    },
    {
        firstArg: '0x13f',
        secondArg: 'qMq4',
        script: '_0x32f1("0x13f", "qMq4")',
        result: 'process',
    },
    {
        firstArg: '0x140',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x140", "SB@Q")',
        result: 'WebAssembly',
    },
    {
        firstArg: '0x141',
        secondArg: '^h6e',
        script: '_0x32f1("0x141", "^h6e")',
        result: 'exists',
    },
    {
        firstArg: '0x142',
        secondArg: 'eSAb',
        script: '_0x32f1("0x142", "eSAb")',
        result: "require('fs')",
    },
    {
        firstArg: '0x143',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x143", "K]Ws")',
        result: 'exists',
    },
    {
        firstArg: '0x144',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x144", "K]Ws")',
        result: 'ntQ',
    },
    {
        firstArg: '0x145',
        secondArg: 'fo7J',
        script: '_0x32f1("0x145", "fo7J")',
        result: 'globalThis==global',
    },
    {
        firstArg: '0x146',
        secondArg: '4!X[',
        script: '_0x32f1("0x146", "4!X[")',
        result: 'value',
    },
    {
        firstArg: '0x147',
        secondArg: '*BCO',
        script: '_0x32f1("0x147", "*BCO")',
        result: 'wvf',
    },
    {
        firstArg: '0x148',
        secondArg: 'M6RB',
        script: '_0x32f1("0x148", "M6RB")',
        result: 'window.toString()',
    },
    {
        firstArg: '0x111',
        secondArg: 'hHMm',
        script: '_0x32f1("0x111", "hHMm")',
        result: 'value',
    },
    {
        firstArg: '0x149',
        secondArg: 'fjzy',
        script: '_0x32f1("0x149", "fjzy")',
        result: 'toString',
    },
    {
        firstArg: '0x14a',
        secondArg: 'RCFI',
        script: '_0x32f1("0x14a", "RCFI")',
        result: 'navigator.cpuClass',
    },
    {
        firstArg: '0x14b',
        secondArg: 'hHMm',
        script: '_0x32f1("0x14b", "hHMm")',
        result: 'exists',
    },
    {
        firstArg: '0x14c',
        secondArg: 'hAPU',
        script: '_0x32f1("0x14c", "hAPU")',
        result: 'cpuClass',
    },
    {
        firstArg: '0x14d',
        secondArg: 'EECj',
        script: '_0x32f1("0x14d", "EECj")',
        result: 'navigator.oscpu',
    },
    {
        firstArg: '0x14e',
        secondArg: 'fo7J',
        script: '_0x32f1("0x14e", "fo7J")',
        result: 'exists',
    },
    {
        firstArg: '0x14f',
        secondArg: 'ErAG',
        script: '_0x32f1("0x14f", "ErAG")',
        result: 'oscpu',
    },
    {
        firstArg: '0x150',
        secondArg: 'y1KF',
        script: '_0x32f1("0x150", "y1KF")',
        result: 'navigator.connection',
    },
    {
        firstArg: '0x151',
        secondArg: 'ieO2',
        script: '_0x32f1("0x151", "ieO2")',
        result: 'exists',
    },
    {
        firstArg: '0x152',
        secondArg: ']ecs',
        script: '_0x32f1("0x152", "]ecs")',
        result: 'connection',
    },
    {
        firstArg: '0x153',
        secondArg: 'lZot',
        script: '_0x32f1("0x153", "lZot")',
        result: "navigator.language=='C'",
    },
    {
        firstArg: '0x154',
        secondArg: '*BCO',
        script: '_0x32f1("0x154", "*BCO")',
        result: 'value',
    },
    {
        firstArg: '0x155',
        secondArg: 'E[@b',
        script: '_0x32f1("0x155", "E[@b")',
        result: 'pIi',
    },
    {
        firstArg: '0x156',
        secondArg: 'fjzy',
        script: '_0x32f1("0x156", "fjzy")',
        result: 'language',
    },
    {
        firstArg: '0x157',
        secondArg: 'QA4[',
        script: '_0x32f1("0x157", "QA4[")',
        result: 'Object.keys(window).length',
    },
    {
        firstArg: '0x158',
        secondArg: 'E[@b',
        script: '_0x32f1("0x158", "E[@b")',
        result: 'value',
    },
    {
        firstArg: '0x159',
        secondArg: 'eSAb',
        script: '_0x32f1("0x159", "eSAb")',
        result: 'numberA',
    },
    {
        firstArg: '0x15a',
        secondArg: 'PVM9',
        script: '_0x32f1("0x15a", "PVM9")',
        result: 'keys',
    },
    {
        firstArg: '0x15b',
        secondArg: '&9]!',
        script: '_0x32f1("0x15b", "&9]!")',
        result: 'numberA',
    },
    {
        firstArg: '0x42',
        secondArg: 'hHMm',
        script: '_0x32f1("0x42", "hHMm")',
        result: 'length',
    },
    {
        firstArg: '0x15c',
        secondArg: '6V&2',
        script: '_0x32f1("0x15c", "6V&2")',
        result: 'window.outerWidth==0',
    },
    {
        firstArg: '0x15d',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x15d", "Y(gg")',
        result: 'value',
    },
    {
        firstArg: '0x15e',
        secondArg: 'C)%p',
        script: '_0x32f1("0x15e", "C)%p")',
        result: 'cuW',
    },
    {
        firstArg: '0x15f',
        secondArg: 'eSAb',
        script: '_0x32f1("0x15f", "eSAb")',
        result: 'outerWidth',
    },
    {
        firstArg: '0x160',
        secondArg: 'M6RB',
        script: '_0x32f1("0x160", "M6RB")',
        result: 'window.outerHeight==0',
    },
    {
        firstArg: '0x161',
        secondArg: 'TER%',
        script: '_0x32f1("0x161", "TER%")',
        result: 'value',
    },
    {
        firstArg: '0x162',
        secondArg: 'EECj',
        script: '_0x32f1("0x162", "EECj")',
        result: 'cuW',
    },
    {
        firstArg: '0x163',
        secondArg: 'QA4[',
        script: '_0x32f1("0x163", "QA4[")',
        result: 'outerHeight',
    },
    {
        firstArg: '0x164',
        secondArg: '4hK1',
        script: '_0x32f1("0x164", "4hK1")',
        result: 'window.WebGLRenderingContext',
    },
    {
        firstArg: '0x165',
        secondArg: ']ecs',
        script: '_0x32f1("0x165", "]ecs")',
        result: 'exists',
    },
    {
        firstArg: '0x166',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x166", "K]Ws")',
        result: 'WebGLRenderingContext',
    },
    {
        firstArg: '0x167',
        secondArg: 'qMq4',
        script: '_0x32f1("0x167", "qMq4")',
        result: 'window.constructor.toString()',
    },
    {
        firstArg: '0x10a',
        secondArg: 'fo7J',
        script: '_0x32f1("0x10a", "fo7J")',
        result: 'value',
    },
    {
        firstArg: '0x168',
        secondArg: '4!X[',
        script: '_0x32f1("0x168", "4!X[")',
        result: 'constructor',
    },
    {
        firstArg: '0x169',
        secondArg: 'E[@b',
        script: '_0x32f1("0x169", "E[@b")',
        result: 'toString',
    },
    {
        firstArg: '0x16a',
        secondArg: '^h6e',
        script: '_0x32f1("0x16a", "^h6e")',
        result: "Boolean(typeof process !== 'undefined' && process.versions && process.versions.node)",
    },
    {
        firstArg: '0x16b',
        secondArg: 'e3R0',
        script: '_0x32f1("0x16b", "e3R0")',
        result: 'value',
    },
    {
        firstArg: '0x16c',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x16c", "SB@Q")',
        result: 'ntQ',
    },
    {
        firstArg: '0x16d',
        secondArg: ']uNf',
        script: '_0x32f1("0x16d", "]uNf")',
        result: 'NvK',
    },
    {
        firstArg: '0x16e',
        secondArg: 'e3R0',
        script: '_0x32f1("0x16e", "e3R0")',
        result: 'undefined',
    },
    {
        firstArg: '0x16f',
        secondArg: '@p]j',
        script: '_0x32f1("0x16f", "@p]j")',
        result: 'versions',
    },
    {
        firstArg: '0x170',
        secondArg: '4hK1',
        script: '_0x32f1("0x170", "4hK1")',
        result: 'versions',
    },
    {
        firstArg: '0x171',
        secondArg: 'Kx0j',
        script: '_0x32f1("0x171", "Kx0j")',
        result: 'node',
    },
    {
        firstArg: '0x172',
        secondArg: 'Kx0j',
        script: '_0x32f1("0x172", "Kx0j")',
        result: 'document.documentMode',
    },
    {
        firstArg: '0x161',
        secondArg: 'TER%',
        script: '_0x32f1("0x161", "TER%")',
        result: 'value',
    },
    {
        firstArg: '0x173',
        secondArg: 'wSBw',
        script: '_0x32f1("0x173", "wSBw")',
        result: 'documentMode',
    },
    {
        firstArg: '0x174',
        secondArg: 'eSAb',
        script: '_0x32f1("0x174", "eSAb")',
        result: 'eval.toString().length',
    },
    {
        firstArg: '0x161',
        secondArg: 'TER%',
        script: '_0x32f1("0x161", "TER%")',
        result: 'value',
    },
    {
        firstArg: '0x175',
        secondArg: 'hHMm',
        script: '_0x32f1("0x175", "hHMm")',
        result: 'toString',
    },
    {
        firstArg: '0x176',
        secondArg: 'B^5n',
        script: '_0x32f1("0x176", "B^5n")',
        result: 'length',
    },
    {
        firstArg: '0x177',
        secondArg: '&%YX',
        script: '_0x32f1("0x177", "&%YX")',
        result: 'navigator.connection.rtt',
    },
    {
        firstArg: '0x15d',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x15d", "Y(gg")',
        result: 'value',
    },
    {
        firstArg: '0x178',
        secondArg: '@p]j',
        script: '_0x32f1("0x178", "@p]j")',
        result: 'connection',
    },
    {
        firstArg: '0x179',
        secondArg: 'TER%',
        script: '_0x32f1("0x179", "TER%")',
        result: 'rtt',
    },
    {
        firstArg: '0x17a',
        secondArg: 'hAPU',
        script: '_0x32f1("0x17a", "hAPU")',
        result: 'deviceType',
    },
    {
        firstArg: '0x17b',
        secondArg: 'lZot',
        script: '_0x32f1("0x17b", "lZot")',
        result: 'function',
    },
    {
        firstArg: '0x17c',
        secondArg: '9xgR',
        script: '_0x32f1("0x17c", "9xgR")',
        result: 'screen.width',
    },
    {
        firstArg: '0x17d',
        secondArg: 'C)%p',
        script: '_0x32f1("0x17d", "C)%p")',
        result: 'value',
    },
    {
        firstArg: '0x17e',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x17e", "Y(gg")',
        result: 'width',
    },
    {
        firstArg: '0x17f',
        secondArg: 'B^5n',
        script: '_0x32f1("0x17f", "B^5n")',
        result: 'screen.height',
    },
    {
        firstArg: '0x180',
        secondArg: 'M6RB',
        script: '_0x32f1("0x180", "M6RB")',
        result: 'value',
    },
    {
        firstArg: '0x181',
        secondArg: '9xgR',
        script: '_0x32f1("0x181", "9xgR")',
        result: 'height',
    },
    {
        firstArg: '0x182',
        secondArg: '6V&2',
        script: '_0x32f1("0x182", "6V&2")',
        result: 'eoapi',
    },
    {
        firstArg: '0x105',
        secondArg: 'RCFI',
        script: '_0x32f1("0x105", "RCFI")',
        result: 'exists',
    },
    {
        firstArg: '0x183',
        secondArg: 'B^5n',
        script: '_0x32f1("0x183", "B^5n")',
        result: 'eoapi_VerifyThis',
    },
    {
        firstArg: '0x141',
        secondArg: '^h6e',
        script: '_0x32f1("0x141", "^h6e")',
        result: 'exists',
    },
    {
        firstArg: '0x184',
        secondArg: 'Y)S$',
        script: '_0x32f1("0x184", "Y)S$")',
        result: 'eoapi_extInvoke',
    },
    {
        firstArg: '0x143',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x143", "K]Ws")',
        result: 'exists',
    },
    {
        firstArg: '0x185',
        secondArg: 'OzL2',
        script: '_0x32f1("0x185", "OzL2")',
        result: 'eoWebBrowserDispatcher',
    },
    {
        firstArg: '0x11b',
        secondArg: '0MG!',
        script: '_0x32f1("0x11b", "0MG!")',
        result: 'exists',
    },
    {
        firstArg: '0x186',
        secondArg: 'RCFI',
        script: '_0x32f1("0x186", "RCFI")',
        result: 'window.HIDDEN_CLASS',
    },
    {
        firstArg: '0x123',
        secondArg: 'wSBw',
        script: '_0x32f1("0x123", "wSBw")',
        result: 'exists',
    },
    {
        firstArg: '0x187',
        secondArg: 'QA4[',
        script: '_0x32f1("0x187", "QA4[")',
        result: 'HIDDEN_CLASS',
    },
    {
        firstArg: '0x188',
        secondArg: '&9]!',
        script: '_0x32f1("0x188", "&9]!")',
        result: 'navigator.mimeTypes.length==2',
    },
    {
        firstArg: '0x189',
        secondArg: '^h6e',
        script: '_0x32f1("0x189", "^h6e")',
        result: 'value',
    },
    {
        firstArg: '0x18a',
        secondArg: 'B^5n',
        script: '_0x32f1("0x18a", "B^5n")',
        result: 'cuW',
    },
    {
        firstArg: '0x18b',
        secondArg: '@p]j',
        script: '_0x32f1("0x18b", "@p]j")',
        result: 'mimeTypes',
    },
    {
        firstArg: '0x18c',
        secondArg: '*BCO',
        script: '_0x32f1("0x18c", "*BCO")',
        result: 'length',
    },
    {
        firstArg: '0x18d',
        secondArg: 'plp9',
        script: '_0x32f1("0x18d", "plp9")',
        result: 'navigator.plugins.length==2',
    },
    {
        firstArg: '0x158',
        secondArg: 'E[@b',
        script: '_0x32f1("0x158", "E[@b")',
        result: 'value',
    },
    {
        firstArg: '0x18e',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x18e", "K]Ws")',
        result: 'TZZ',
    },
    {
        firstArg: '0x18f',
        secondArg: '6V&2',
        script: '_0x32f1("0x18f", "6V&2")',
        result: 'plugins',
    },
    {
        firstArg: '0x190',
        secondArg: 'orkc',
        script: '_0x32f1("0x190", "orkc")',
        result: 'length',
    },
    {
        firstArg: '0x191',
        secondArg: 'fjzy',
        script: '_0x32f1("0x191", "fjzy")',
        result: 'window.globalThis',
    },
    {
        firstArg: '0x192',
        secondArg: 'tmku',
        script: '_0x32f1("0x192", "tmku")',
        result: 'exists',
    },
    {
        firstArg: '0x193',
        secondArg: '4hK1',
        script: '_0x32f1("0x193", "4hK1")',
        result: 'globalThis',
    },
    {
        firstArg: '0x194',
        secondArg: 'SB@Q',
        script: '_0x32f1("0x194", "SB@Q")',
        result: 'navigator.userAgentData.brands[0].brand',
    },
    {
        firstArg: '0x195',
        secondArg: 'ieO2',
        script: '_0x32f1("0x195", "ieO2")',
        result: 'value',
    },
    {
        firstArg: '0x196',
        secondArg: 'RCFI',
        script: '_0x32f1("0x196", "RCFI")',
        result: 'userAgentData',
    },
    {
        firstArg: '0x197',
        secondArg: 'nWG6',
        script: '_0x32f1("0x197", "nWG6")',
        result: 'brands',
    },
    {
        firstArg: '0x198',
        secondArg: 'y1KF',
        script: '_0x32f1("0x198", "y1KF")',
        result: 'brand',
    },
    {
        firstArg: '0x199',
        secondArg: '6)P!',
        script: '_0x32f1("0x199", "6)P!")',
        result: 'navigator.userAgentData.brands[1].brand',
    },
    {
        firstArg: '0x146',
        secondArg: '4!X[',
        script: '_0x32f1("0x146", "4!X[")',
        result: 'value',
    },
    {
        firstArg: '0x19a',
        secondArg: 'B^5n',
        script: '_0x32f1("0x19a", "B^5n")',
        result: 'userAgentData',
    },
    {
        firstArg: '0x19b',
        secondArg: '^h6e',
        script: '_0x32f1("0x19b", "^h6e")',
        result: 'brands',
    },
    {
        firstArg: '0x19c',
        secondArg: 'Y(gg',
        script: '_0x32f1("0x19c", "Y(gg")',
        result: 'brand',
    },
    {
        firstArg: '0x19d',
        secondArg: '&%YX',
        script: '_0x32f1("0x19d", "&%YX")',
        result: 'navigator.userAgentData.brands[2].brand',
    },
    {
        firstArg: '0x111',
        secondArg: 'hHMm',
        script: '_0x32f1("0x111", "hHMm")',
        result: 'value',
    },
    {
        firstArg: '0x19e',
        secondArg: 'qMq4',
        script: '_0x32f1("0x19e", "qMq4")',
        result: 'userAgentData',
    },
    {
        firstArg: '0x19f',
        secondArg: '4!X[',
        script: '_0x32f1("0x19f", "4!X[")',
        result: 'brands',
    },
    {
        firstArg: '0x1a0',
        secondArg: ']Y49',
        script: '_0x32f1("0x1a0", "]Y49")',
        result: 'brand',
    },
    {
        firstArg: '0x1a1',
        secondArg: 'tmku',
        script: '_0x32f1("0x1a1", "tmku")',
        result: "navigator.plugins['Microsoft Edge PDF Plugin']",
    },
    {
        firstArg: '0x119',
        secondArg: 'OzL2',
        script: '_0x32f1("0x119", "OzL2")',
        result: 'exists',
    },
    {
        firstArg: '0x1a2',
        secondArg: 'wSBw',
        script: '_0x32f1("0x1a2", "wSBw")',
        result: 'plugins',
    },
    {
        firstArg: '0x1a3',
        secondArg: 'nWG6',
        script: '_0x32f1("0x1a3", "nWG6")',
        result: 'Microsoft Edge PDF Plugin',
    },
    {
        firstArg: '0x1a4',
        secondArg: '&%YX',
        script: '_0x32f1("0x1a4", "&%YX")',
        result: 'navigator.brave',
    },
    {
        firstArg: '0x165',
        secondArg: ']ecs',
        script: '_0x32f1("0x165", "]ecs")',
        result: 'exists',
    },
    {
        firstArg: '0x1a5',
        secondArg: 'e3R0',
        script: '_0x32f1("0x1a5", "e3R0")',
        result: 'brave',
    },
    {
        firstArg: '0x1a6',
        secondArg: 'fo7J',
        script: '_0x32f1("0x1a6", "fo7J")',
        result: 'navigator.userAgentData.mobile',
    },
    {
        firstArg: '0x1a7',
        secondArg: 'hAPU',
        script: '_0x32f1("0x1a7", "hAPU")',
        result: 'value',
    },
    {
        firstArg: '0x1a8',
        secondArg: 'EECj',
        script: '_0x32f1("0x1a8", "EECj")',
        result: 'userAgentData',
    },
    {
        firstArg: '0x1a9',
        secondArg: 'ieO2',
        script: '_0x32f1("0x1a9", "ieO2")',
        result: 'mobile',
    },
    {
        firstArg: '0x1aa',
        secondArg: '0MG!',
        script: '_0x32f1("0x1aa", "0MG!")',
        result: 'navigator.userAgentData.platform',
    },
    {
        firstArg: '0x1ab',
        secondArg: 'Qv[c',
        script: '_0x32f1("0x1ab", "Qv[c")',
        result: 'value',
    },
    {
        firstArg: '0x1ac',
        secondArg: 'M6RB',
        script: '_0x32f1("0x1ac", "M6RB")',
        result: 'userAgentData',
    },
    {
        firstArg: '0x1ad',
        secondArg: 'nWG6',
        script: '_0x32f1("0x1ad", "nWG6")',
        result: 'platform',
    },
    {
        firstArg: '0x1ae',
        secondArg: 'fjzy',
        script: '_0x32f1("0x1ae", "fjzy")',
        result: '11|9|0|2|10|8|13|1|7|4|3|12|5|6',
    },
    {
        firstArg: '0xc',
        secondArg: 'hHMm',
        script: '_0x32f1("0xc", "hHMm")',
        result: 'split',
    },
    {
        firstArg: '0x1af',
        secondArg: 'e3R0',
        script: '_0x32f1("0x1af", "e3R0")',
        result: 'MPW',
    },
    {
        firstArg: '0x1b0',
        secondArg: 'C)%p',
        script: '_0x32f1("0x1b0", "C)%p")',
        result: 'QdF',
    },
    {
        firstArg: '0x1b1',
        secondArg: 'Kax[',
        script: '_0x32f1("0x1b1", "Kax[")',
        result: 'substr',
    },
    {
        firstArg: '0x1b2',
        secondArg: ']ecs',
        script: '_0x32f1("0x1b2", "]ecs")',
        result: 'v1ba1d6ae1666c061dd1958c7aed4f24735e2a2b4d9bc83d967b7eae3a580b462',
    },
    {
        firstArg: '0x1b3',
        secondArg: 'fo7J',
        script: '_0x32f1("0x1b3", "fo7J")',
        result: 'QdF',
    },
    {
        firstArg: '0x1b4',
        secondArg: 'TER%',
        script: '_0x32f1("0x1b4", "TER%")',
        result: 'substr',
    },
    {
        firstArg: '0x1b5',
        secondArg: 'orkc',
        script: '_0x32f1("0x1b5", "orkc")',
        result: 'VUE',
    },
    {
        firstArg: '0xbc',
        secondArg: 'tmku',
        script: '_0x32f1("0xbc", "tmku")',
        result: 'length',
    },
    {
        firstArg: '0x1b6',
        secondArg: '9xgR',
        script: '_0x32f1("0x1b6", "9xgR")',
        result: 'push',
    },
    {
        firstArg: '0x111',
        secondArg: 'hHMm',
        script: '_0x32f1("0x111", "hHMm")',
        result: 'value',
    },
    {
        firstArg: '0x1b7',
        secondArg: '9xgR',
        script: '_0x32f1("0x1b7", "9xgR")',
        result: 'ntQ',
    },
    {
        firstArg: '0x1b8',
        secondArg: 'tmku',
        script: '_0x32f1("0x1b8", "tmku")',
        result: 'Mfh',
    },
    {
        firstArg: '0x1b9',
        secondArg: 'D6b8',
        script: '_0x32f1("0x1b9", "D6b8")',
        result: 'createElement',
    },
    {
        firstArg: '0x1ba',
        secondArg: 'C)%p',
        script: '_0x32f1("0x1ba", "C)%p")',
        result: 'img',
    },
    {
        firstArg: '0x1bb',
        secondArg: '0MG!',
        script: '_0x32f1("0x1bb", "0MG!")',
        result: 'src',
    },
    {
        firstArg: '0x1bc',
        secondArg: 'e3R0',
        script: '_0x32f1("0x1bc", "e3R0")',
        result: '/_Incapsula_Resource?SWKMTFSR=1&e=',
    },
    {
        firstArg: '0x1bd',
        secondArg: 'D6b8',
        script: '_0x32f1("0x1bd", "D6b8")',
        result: 'Math',
    },
    {
        firstArg: '0x1be',
        secondArg: 'nWG6',
        script: '_0x32f1("0x1be", "nWG6")',
        result: 'random',
    },
    {
        firstArg: '0x1bf',
        secondArg: 'lJ]t',
        script: '_0x32f1("0x1bf", "lJ]t")',
        result: 'N37vv71AL++/ve+/vXvvv70K77+9MhTvv71pxbVp',
    },
    {
        firstArg: '0x1c0',
        secondArg: ']uNf',
        script: '_0x32f1("0x1c0", "]uNf")',
        result: 'btoa',
    },
    {
        firstArg: '0x1c1',
        secondArg: '&9]!',
        script: '_0x32f1("0x1c1", "&9]!")',
        result: 'btoa',
    },
    {
        firstArg: '0x1c2',
        secondArg: 'nWG6',
        script: '_0x32f1("0x1c2", "nWG6")',
        result: 'push',
    },
    {
        firstArg: '0x1c3',
        secondArg: 'qMq4',
        script: '_0x32f1("0x1c3", "qMq4")',
        result: 'mbr',
    },
    {
        firstArg: '0x1c4',
        secondArg: 'hAPU',
        script: '_0x32f1("0x1c4", "hAPU")',
        result: 'gek',
    },
    {
        firstArg: '0x1c5',
        secondArg: 'Y)S$',
        script: '_0x32f1("0x1c5", "Y)S$")',
        result: 'gek',
    },
    {
        firstArg: '0x1c6',
        secondArg: 'orkc',
        script: '_0x32f1("0x1c6", "orkc")',
        result: '.toString()',
    },
    {
        firstArg: '0x1c7',
        secondArg: ']Y49',
        script: '_0x32f1("0x1c7", "]Y49")',
        result: 'value',
    },
    {
        firstArg: '0x1c8',
        secondArg: 'B^5n',
        script: '_0x32f1("0x1c8", "B^5n")',
        result: 'toString',
    },
    {
        firstArg: '0x1c9',
        secondArg: 'ErAG',
        script: '_0x32f1("0x1c9", "ErAG")',
        result: 'log',
    },
    {
        firstArg: '0x1ca',
        secondArg: 'QA4[',
        script: '_0x32f1("0x1ca", "QA4[")',
        result: 'Mfh',
    },
    {
        firstArg: '0x1cb',
        secondArg: 'V%v2',
        script: '_0x32f1("0x1cb", "V%v2")',
        result: 'Mfh',
    },
    {
        firstArg: '0x1cc',
        secondArg: 'C)%p',
        script: '_0x32f1("0x1cc", "C)%p")',
        result: 'Mfh',
    },
    {
        firstArg: '0x1cd',
        secondArg: 'B^5n',
        script: '_0x32f1("0x1cd", "B^5n")',
        result: 'createElement',
    },
    {
        firstArg: '0x1ce',
        secondArg: '*BCO',
        script: '_0x32f1("0x1ce", "*BCO")',
        result: 'img',
    },
    {
        firstArg: '0x1cf',
        secondArg: 'K]Ws',
        script: '_0x32f1("0x1cf", "K]Ws")',
        result: 'src',
    },
    {
        firstArg: '0x1d0',
        secondArg: 'qMq4',
        script: '_0x32f1("0x1d0", "qMq4")',
        result: '/_Incapsula_Resource?SSATYUBA=jse:',
    },
    {
        firstArg: '0x1d1',
        secondArg: 'D6b8',
        script: '_0x32f1("0x1d1", "D6b8")',
        result: 'btoa',
    },
    {
        firstArg: '0x1d2',
        secondArg: 'EECj',
        script: '_0x32f1("0x1d2", "EECj")',
        result: 'message',
    },
    {
        firstArg: '0x1d3',
        secondArg: '&9]!',
        script: '_0x32f1("0x1d3", "&9]!")',
        result: 'log',
    },
];

traverse(ast, {
    CallExpression(path) {
        if (path.node.callee.type === 'Identifier' && path.node.callee.name === '_0x32f1') {
            const firstArg = path.node.arguments[0].value;
            const secondArg = path.node.arguments[1].value;

            const callResult = callsWithValues.find(
                (call) => call.firstArg === firstArg && call.secondArg === secondArg
            );
            if (callResult) {
                path.replaceWith(types.stringLiteral(callResult.result));
            }
        }
    },
});

const outputCode = generate(ast, { retainLines: false }).code;

const deobfedScript = deobfuscate(outputCode, {
    objectSimplification: { isEnabled: true },
    objectPacking: { isEnabled: true },
    proxyFunctionInlining: { isEnabled: true },
    stringRevealing: { isEnabled: true },
    expressionSimplification: { isEnabled: true },
    constantPropagation: { isEnabled: true },
    reassignmentRemoval: { isEnabled: true },
    sequenceSplitting: { isEnabled: true },
    controlFlowRecovery: { isEnabled: true },
    deadBranchRemoval: { isEnabled: false },
    antiTamperRemoval: { isEnabled: true },
    unusedVariableRemoval: { isEnabled: true },
    propertySimplification: { isEnabled: true },
});

const outputPath = '_Incapsula_Resource.transformed.js';
const prettier = await import('prettier');
const prettierConfig = await prettier.resolveConfig(outputPath);
const formatted = await prettier.format(deobfedScript, {
    ...prettierConfig,
    filepath: outputPath,
});

await fs.writeFile(outputPath, formatted);
